---
name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Nuclei
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ‘http://213.168.250.216’
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}